### ISSUE TITLE
Instructions on how to compile the kernel

### ISSUE THREAD

**Issue by therealjr** [ssrg-vt/popcorn-kernel#110]
I've been trying to compile the kernel but am met with many errors. I was resolving them but now there's no information to point me in any direction on how to resolve this issue. Could someone provide a tutorial on compiling the kernel?

**Comment by xjtuwxg** [comment]
Hello, we are recently in transit to a new kernel version and a new compiler version. Please find this new document that may help you: https://popcornlinux-doc.readthedocs.io
