### ISSUE TITLE
No bzImage 

### ISSUE THREAD

**Issue by therealjr** [ssrg-vt/popcorn-kernel#111]
I ran:

git clone --depth=1 -b main --single-branch https://github.com/ssrg-vt/popcorn-kernel.git linux-x86
cp linux-x86/kernel/popcorn/configs/config-x86_64-qemu linux-x86/.config
make -C linux-x86 -j8

then:

sudo qemu-system-x86_64 \
    -enable-kvm -cpu host -smp 2 -m 4096 -nographic \
    -drive id=root,media=disk,file=x86.img \
    -net nic,macaddr=00:da:bc:de:00:13 -net tap,ifname=tap0,script=no \
    -kernel linux-x86/arch/x86/boot/bzImage \
    -append "root=/dev/sda rw console=ttyS0" \
    -pidfile vm0.pid 2>&1 | tee vm0.log

and I get an error that there was no bzImage. I checked in the directory and indeed it is missing. 

I'm following the instructions from https://popcornlinux-doc.readthedocs.io/en/latest/build_kernel.html#running-popcorn-linux-on-qemu-virtual-machines-recommended

Has anyone else ran into this?

**Comment by xjtuwxg** [comment]
Can you find this file `linux-x86/arch/x86/boot/bzImage` after you built the kernel?

**Comment by therealjr** [comment]
No

**Comment by xjtuwxg** [comment]
Could you try to build the kernel without multithreading, like `make -C linux-x86`, and let us know the error.

**Comment by therealjr** [comment]
github will not let me post all of the error message so I'm posting it to a 3rd party site:

https://paste.ofcode.org/CyurvvMxntVWwrVPYVcRy7

**Comment by xjtuwxg** [comment]
It seems this is a gcc-9 bug. Could you try to switch to gcc-8 as in this link: https://bugs.launchpad.net/ubuntu/+source/gcc-9/+bug/1830961

**Comment by therealjr** [comment]
For those of you who have experienced that issue install gcc-8 as suggested and follow this tutorial to reconfigure gcc to use 8:

https://askubuntu.com/questions/1028601/install-gcc-8-only-on-ubuntu-18-04
