### ISSUE TITLE
Non-hardcoded popcorn_msg driver IP address

### ISSUE THREAD

**Issue by bxatnarf** [ssrg-vt/popcorn-kernel#38]
IP addresses are currently [hardcoded](https://github.com/ssrg-vt/popcorn-kernel/blob/9f7418b341eb51053f970863caebf51b1a2ecef9/msg_layer/config.h#L8) into the popcorn_message driver.  Such configuration should not be hardcoded.  We should consider using existing networking mechanisms to achieve the same goal.

**Comment by ahughes12** [comment]
Going to close this now as we have functionality to read from configuration files in the merge branch. That code is [here](https://github.com/ssrg-vt/popcorn-kernel/blob/merge/msg_layer/socket.c#L502). By default it reads a file from `/etc/popcorn/nodes`, with one IP address per node per line.
