### ISSUE TITLE
Null pointer dereference if msg_socket module only partially loaded

### ISSUE THREAD

**Issue by bxatnarf** [ssrg-vt/popcorn-kernel#62]
I've noticed this on arm, but I imagine this holds true for x86.

If `insmod msg_socked.ko` is called and killed before the module is fully loaded, the following shows up in the kernel log:
'''
[   63.629363] Loading Popcorn messaging layer over TCP/IP...
[   63.629563] popcorn: Loading node configuration...
[   63.629868] popcorn: * 0: 10.4.4.100
[   63.630049] popcorn:   1: 10.4.4.101
[   63.631035] Ready to accept incoming connections
[  139.699688] Failed to accept, -512
[  139.700003] Unable to handle kernel NULL pointer dereference at virtual address 0000000000000028
[  139.700293] Mem abort info:
[  139.700389]   ESR = 0x96000004
[  139.700513]   Exception class = DABT (current EL), IL = 32 bits
[  139.701057]   SET = 0, FnV = 0
[  139.701190]   EA = 0, S1PTW = 0
[  139.701281] Data abort info:
[  139.701377]   ISV = 0, ISS = 0x00000004
[  139.701508]   CM = 0, WnR = 0
[  139.701638] user pgtable: 4k pages, 48-bit VAs, pgdp = (____ptrval____)
[  139.701924] [0000000000000028] pgd=0000000000000000
[  139.702289] Internal error: Oops: 96000004 [#1] SMP
[  139.702535] Modules linked in: msg_socket(+)
[  139.702927] CPU: 0 PID: 255 Comm: insmod Not tainted 4.19.0-rc5-popcorn+ #17
[  139.703164] Hardware name: linux,dummy-virt (DT)
[  139.703419] pstate: 40000005 (nZcv daif -PAN -UAO)
[  139.703577] pc : __sock_release+0x1c/0xc0
[  139.703704] lr : sock_release+0x24/0x30
[  139.703832] sp : ffff000009033ac0
[  139.703944] x29: ffff000009033ac0 x28: ffff0000005b2400 
[  139.704158] x27: 000000000000000b x26: 0000000000000001 
[  139.704322] x25: 0000000000000001 x24: ffff0000089085c8 
[  139.704480] x23: 0000000000000000 x22: 0000000000000001 
[  139.704643] x21: 0000000000000000 x20: 0000000000000000 
[  139.704857] x19: 0000000000000000 x18: 0000000000000010 
[  139.705010] x17: 0000000000000000 x16: 0000000000000000 
[  139.705164] x15: ffffffffffffffff x14: ffff0000089085c8 
[  139.705317] x13: ffff0000889c6027 x12: ffff0000089c602f 
[  139.705462] x11: ffff000008922000 x10: ffff000009033810 
[  139.705615] x9 : 00000000ffffffd0 x8 : ffff000008441fc8 
[  139.705769] x7 : 0000000000000005 x6 : 0000000000000070 
[  139.705943] x5 : 0000000000000000 x4 : 0000000000000000 
[  139.706113] x3 : 0000000000000000 x2 : 42f4e4c09f614200 
[  139.706267] x1 : 0000000000000000 x0 : ffff00000849255c 
[  139.706479] Process insmod (pid: 255, stack limit = 0x(____ptrval____))
[  139.706756] Call trace:
[  139.706897]  __sock_release+0x1c/0xc0
[  139.707021]  sock_release+0x24/0x30
[  139.707450]  init_kmsg_sock+0x3c8/0xde0 [msg_socket]
[  139.707608]  do_one_initcall+0x54/0x1d8
[  139.707726]  do_init_module+0x60/0x1f0
[  139.707851]  load_module+0x1ef0/0x23b8
[  139.707965]  __se_sys_finit_module+0xa0/0xf8
[  139.708103]  __arm64_sys_finit_module+0x24/0x30
[  139.708242]  el0_svc_common+0x94/0xe8
[  139.708354]  el0_svc_handler+0x38/0x80
[  139.708469]  el0_svc+0x8/0xc
[  139.708711] Code: aa0003f3 aa0103f4 aa1e03e0 d503201f (f9401660) 
[  139.709124] ---[ end trace 71ae27f020a2838e ]---
'''

**Comment by ahughes12** [comment]
Checked back in on this issue with the current code in the merge branch. Currently am getting feedback that the kernel might be being unloaded currently (see #85 for a similar issue). 

```popcorn@x86:~$ sudo insmod msg_socket.ko 
[  T661] msg_socket: loading out-of-tree module taints kernel.
[  T661] Loading Popcorn messaging layer over TCP/IP...
[  T661] popcorn: Loading node configuration...
[  T661] popcorn: * 0: 192.168.122.2
[  T661] popcorn:   1: 192.168.122.3
[  T661] Ready to accept incoming connections
[  T661] Failed to accept, -512
[  T661] Successfully unloaded module!
[  T661] BUG: unable to handle page fault for address: ffff8880588ed000
[  T661] #PF: supervisor write access in kernel mode
[  T661] #PF: error_code(0x000b) - reserved bit violation
[  T661] PGD 2e01067 P4D 2e01067 PUD 2e04067 PMD 5897b063 PTE 800fffffa7712063
[  T661] Oops: 000b [#1] SMP NOPTI
[  T661] CPU: 0 PID: 661 Comm: insmod Tainted: G           O      5.2.0-rc4-popcorn+ #31
[  T661] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.10.2-1ubuntu1 04/01/2014
[  T661] RIP: 0010:__tlb_remove_page_size+0x62/0x90
[  T661] Code: 5d c3 83 7f 1c 13 74 3a 31 f6 48 89 fb bf 00 28 00 00 e8 a1 f9 00 00 48 85 c0 74 26 48 b9 00 00 00 00 fe 01 00 00 83 43 1c 01 <48> c7 00 00 00 00 00 48 89 48 08 48 8b 53 20 48 89 02 48 89 43 20
[  T661] RSP: 0018:ffffc90000673b48 EFLAGS: 00000202
[  T661] RAX: ffff8880588ed000 RBX: ffffc90000673c58 RCX: 000001fe00000000
[  T661] RDX: 00000000588ed000 RSI: 0000000000000000 RDI: 0000000000000246
[  T661] RBP: 0000000000000000 R08: 0000000000000000 R09: 0000000000000001
[  T661] R10: 0000000000000000 R11: 0000000000000000 R12: ffffc90000673c58
[  T661] R13: 000055555555b000 R14: ffff88805a326ad8 R15: ffff888058936cf0
[  T661] FS:  0000000000000000(0000) GS:ffff88805ba00000(0000) knlGS:0000000000000000
[  T661] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  T661] CR2: ffff8880588ed000 CR3: 0000000058a44000 CR4: 00000000000006f0
[  T661] Call Trace:
[  T661]  unmap_page_range+0x4e3/0x820
[  T661]  unmap_vmas+0x3c/0x50
[  T661]  exit_mmap+0x8b/0x150
[  T661]  mmput+0x41/0xf0
[  T661]  do_exit+0x2cc/0xc30
[  T661]  do_group_exit+0x39/0xb0
[  T661]  get_signal+0x175/0xca0
[  T661]  do_signal+0x36/0x5d0
[  T661]  ? __se_sys_finit_module+0xd8/0xf0
[  T661]  ? __se_sys_finit_module+0xd8/0xf0
[  T661]  exit_to_usermode_loop+0x9b/0xb0
[  T661]  do_syscall_64+0x2b1/0x440
[  T661]  ? trace_hardirqs_off_thunk+0x1a/0x1c
[  T661]  entry_SYSCALL_64_after_hwframe+0x49/0xbe
[  T661] RIP: 0033:0x7ffff7b155b9
[  T661] Code: 01 00 48 81 c4 80 00 00 00 e9 11 ff ff ff 0f 1f 00 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 9f 08 2c 00 f7 d8 64 89 01 48
[  T661] RSP: 002b:00007fffffffeb38 EFLAGS: 00000202 ORIG_RAX: 0000000000000139
[  T661] RAX: fffffffffffffe00 RBX: 000055555577c220 RCX: 00007ffff7b155b9
[  T661] RDX: 0000000000000000 RSI: 000055555556f3d9 RDI: 0000000000000003
[  T661] RBP: 000055555556f3d9 R08: 0000000000000000 R09: 00007ffff7dd8f20
[  T661] R10: 0000000000000003 R11: 0000000000000202 R12: 0000000000000000
[  T661] R13: 000055555577c1f0 R14: 0000000000000000 R15: 0000000000000000
[  T661] Modules linked in:
[  T661] CR2: ffff8880588ed000
[  T661] ---[ end trace dca72137c7750cd4 ]---
[  T661] RIP: 0010:__tlb_remove_page_size+0x62/0x90
```
