### ISSUE TITLE
Debian package 'crossbuild-essential-arm64' has unreliable source.

### ISSUE THREAD

**Issue by cifranix** [ssrg-vt/popcorn-kernel#88]
When setting up the ARM virtual machine, the host must have the crossbuild-essential-arm64 package, which is found at http://emdebian.org/,  however, this website has been down for several days. 

Solution: 
The .deb package can be obtained here instead: https://packages.debian.org/sid/all/crossbuild-essential-arm64/download

Best,
Nick

**Comment by ahughes12** [comment]
Thanks for raising this. On Ubuntu 18.04 and above, there isn't any need to add a repository outside of the ubuntu repos. I'll update the wiki with newer installation instructions for different versions of ubuntu.

Going to go ahead and close this for now (feel free to re-open for anything/further discussion). Thanks!
